ALTER TABLE EMPLOYEE ADD  MANAGING SMALLINT DEFAULT 1;
ALTER TABLE SECTION ADD  SHOW_IN_MENU VARCHAR(1) DEFAULT 'N';
ALTER TABLE SECTION ADD  LANGUAGE VARCHAR(20) ;
ALTER TABLE USERS ADD   FIRST_TIME_LOGIN VARCHAR(1) DEFAULT 'Y';
ALTER TABLE VISIT ADD APPOINTMENT_ID BIGINT;
ALTER TABLE VISIT ADD CONSTRAINT FOREIGN KEY FK_V_APT_1(APPOINTMENT_ID)  
REFERENCES APPOINTMENT(APPOINTMENT_ID);
--- 06/30/2019   --- 
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 7, 'CONFIG_DATA_TYPE');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, PARENT_CATEGORY_ID, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 7, 7000, 'INT');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, PARENT_CATEGORY_ID, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 7, 7001, 'LONG');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, PARENT_CATEGORY_ID, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 7, 7002, 'STRING');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, PARENT_CATEGORY_ID, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 7, 7003, 'DECIMAL');

ALTER TABLE WEEK_DAY ADD  LANGUAGE VARCHAR(2) ;

ALTER TABLE ADMISSION MODIFY ADMISSION_DATETIME TIMESTAMP;
ALTER TABLE BED_ASSIGNMENT MODIFY START_DATE TIMESTAMP; 
ALTER TABLE BED_ASSIGNMENT MODIFY END_DATE TIMESTAMP; 

--- 07/31/2019    --- 
ALTER TABLE BILL_SERVICE MODIFY PAYER_AMOUNT DOUBLE NULL;

ALTER TABLE LAB_TEST ADD COLUMN PAYER_PRICE DOUBLE NOT NULL;
ALTER TABLE LAB_TEST ADD COLUMN PRICE DOUBLE NOT NULL;

ALTER TABLE SERVICE ADD COLUMN LAB_TEST_ID BIGINT NULL;
ALTER TABLE SERVICE ADD COLUMN MEDICINE_ID BIGINT NULL;


CREATE TABLE PATIENT_SERVICE (
	   PATIENT_SERVICE_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , SERVICE_DATE DATE NOT NULL
	 , ADMISSION_ID BIGINT NULL 
	 , VISIT_ID BIGINT NULL 
	 , SERVICE_ID BIGINT NOT NULL 
	 , NOTES VARCHAR(500)
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (PATIENT_SERVICE_ID)
     , CONSTRAINT FK_PATIENT_SERVICE_1 FOREIGN KEY (ADMISSION_ID)
                  REFERENCES ADMISSION (ADMISSION_ID)
     , CONSTRAINT FK_PATIENT_SERVICE_2 FOREIGN KEY (VISIT_ID)
                  REFERENCES VISIT (VISIT_ID)
     , CONSTRAINT FK_PATIENT_SERVICE_3 FOREIGN KEY (SERVICE_ID)
                  REFERENCES SERVICE (SERVICE_ID)
);


CREATE TABLE PATIENT_PACKAGE (
	   PATIENT_PACKAGE_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , PACKAGE_DATE DATE NOT NULL
	 , ADMISSION_ID BIGINT NULL 
	 , VISIT_ID BIGINT NULL 
	 , PACKAGE_ID BIGINT NOT NULL 
	 , NOTES VARCHAR(500)
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (PATIENT_PACKAGE_ID)
     , CONSTRAINT FK_PATIENT_PACKAGE_1 FOREIGN KEY (ADMISSION_ID)
                  REFERENCES ADMISSION (ADMISSION_ID)
     , CONSTRAINT FK_PATIENT_PACKAGE_2 FOREIGN KEY (VISIT_ID)
                  REFERENCES VISIT (VISIT_ID)
     , CONSTRAINT FK_PATIENT_PACKAGE_3 FOREIGN KEY (PACKAGE_ID)
                  REFERENCES PACKAGE (PACKAGE_ID)
);

INSERT INTO DOCTOR_ORDER_TYPE(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_TYPE_ID, NAME) VALUES (now(), now(), 1, 3, 'MEDICAL');

INSERT INTO DOCTOR_ORDER_TYPE(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_TYPE_ID, NAME) VALUES (now(), now(), 1, 4, 'BED');

ALTER TABLE BILL_SERVICE MODIFY COLUMN SERVICE_ID BIGINT NULL;

ALTER TABLE BILL_SERVICE ADD COLUMN PACKAGE_ID BIGINT NULL;

ALTER TABLE PACKAGE ADD COLUMN RATE DOUBLE NOT NULL;

ALTER TABLE BILL_SERVICE ADD COLUMN DOCTOR_ORDER_TYPE_ID BIGINT NOT NULL;

ALTER TABLE BED ADD COLUMN RATE DOUBLE NOT NULL;

ALTER TABLE BILL_SERVICE ADD COLUMN PRODUCT_ID BIGINT NULL;

ALTER TABLE BILL_SERVICE ADD COLUMN LAB_TEST_ID BIGINT NULL;

ALTER TABLE BILL_SERVICE ADD COLUMN BED_ID BIGINT NULL;



-------------      08/14/2019            ----------------

CREATE TABLE MODALITY (
	   MODALITY_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , NAME VARCHAR(50) NOT NULL
	 , DESCRIPTION VARCHAR(500) NOT NULL
	 , STATUS SMALLINT DEFAULT 0
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (MODALITY_ID)
);

CREATE TABLE BODY_PART (
	   BODY_PART_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , NAME VARCHAR(50) NOT NULL
	 , DESCRIPTION VARCHAR(500) NOT NULL
	 , STATUS SMALLINT DEFAULT 0
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (BODY_PART_ID)
);

CREATE TABLE LATERALITY (
	   LATERALITY_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , NAME VARCHAR(50) NOT NULL
	 , DESCRIPTION VARCHAR(500) NOT NULL
	 , STATUS SMALLINT DEFAULT 0
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (LATERALITY_ID)
);

CREATE TABLE RAD_EXAM (
	   EXAM_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , MODALITY_ID BIGINT NOT NULL 
	 , NAME VARCHAR(50) NOT NULL
	 , DESCRIPTION VARCHAR(500)
	 , RATE DOUBLE NOT NULL DEFAULT 0
	 , STATUS SMALLINT DEFAULT 0
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (EXAM_ID)
     , CONSTRAINT FK_RAD_EXAM_1 FOREIGN KEY (MODALITY_ID)
                  REFERENCES MODALITY (MODALITY_ID)
);

CREATE TABLE RAD_INVESTIGATION (
  	INVESTIGATION_ID BIGINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , DESCRIPTION VARCHAR(250)
  , INVESTIGATION_DATETIME DATE NOT NULL
  , ADMISSION_ID BIGINT
  , VISIT_ID BIGINT
  , DOCTOR_ORDER_ID BIGINT
  , REFERRING_PHYSICIAN_ID BIGINT
  , ASSIGN_TO BIGINT
  , EXAM_ID BIGINT NOT NULL
  , REJECTION_DATETIME TIMESTAMP NULL
  , REJECTION_COMMENTS VARCHAR(1000) 
  , COMPLETE_DATETIME TIMESTAMP NULL
  , COMPLETE_COMMENTS VARCHAR(1000)
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1
  , EXAM_STATUS_ID TINYINT DEFAULT 0
  , PRIMARY KEY (INVESTIGATION_ID)
  , CONSTRAINT FK_RAD_INVESTIGATION_1 FOREIGN KEY (ADMISSION_ID)
                  REFERENCES ADMISSION (ADMISSION_ID)
  , CONSTRAINT FK_RAD_INVESTIGATION_2 FOREIGN KEY (VISIT_ID)
                  REFERENCES VISIT (VISIT_ID)
  , CONSTRAINT FK_RAD_INVESTIGATION_3 FOREIGN KEY (EXAM_ID)
                  REFERENCES RAD_EXAM (EXAM_ID)
  , CONSTRAINT FK_RAD_INVESTIGATION_4 FOREIGN KEY (EXAM_STATUS_ID)
                  REFERENCES EXAM_STATUS (EXAM_STATUS_ID)
  , CONSTRAINT FK_RAD_INVESTIGATION_5 FOREIGN KEY (REFERRING_PHYSICIAN_ID)
                  REFERENCES USERS (USER_ID)
);


CREATE TABLE EXAM_STATUS (
  	EXAM_STATUS_ID TINYINT NOT NULL
  , NAME VARCHAR(20) NOT NULL
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1
  , PRIMARY KEY (EXAM_STATUS_ID)
);

INSERT INTO EXAM_STATUS(EXAM_STATUS_ID, NAME) VALUES (1, 'Ordonné');
INSERT INTO EXAM_STATUS(EXAM_STATUS_ID, NAME) VALUES (2, 'Assigné');
INSERT INTO EXAM_STATUS(EXAM_STATUS_ID, NAME) VALUES (3, 'Rejeté');
INSERT INTO EXAM_STATUS(EXAM_STATUS_ID, NAME) VALUES (4, 'En cours');
INSERT INTO EXAM_STATUS(EXAM_STATUS_ID, NAME) VALUES (5, 'Terminé');

INSERT INTO USER_GROUP(CREATE_DATE, MOD_DATE, MOD_BY, USER_GROUP_ID, NAME) VALUES (now(), now(), 1, 4, 'Radiology Tech');
