INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,1,'AF','Afghanistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,2,'ZA','Afrique du Sud');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,3,'AL','Albanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,4,'DZ','Algerie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,5,'DE','Allemagne');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,6,'AD','Andorre');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,7,'AO','Angola');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,8,'AI','Anguilla');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,9,'AG','Antigua-et-Barbuda');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,10,'AN','Antilles neerlandaises');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,11,'SA','Arabie saoudite');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,12,'AR','Argentine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,13,'AM','Armenie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,14,'AW','Aruba');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,15,'AU','Australie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,16,'AT','Autriche');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,17,'AZ','Azerbaidjan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,18,'BS','Bahamas');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,19,'BH','Bahrein');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,20,'BD','Bangladesh');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,21,'BB','Barbade');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,22,'PW','Belau');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,23,'BE','Belgique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,24,'BZ','Belize');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,25,'BJ','Benin');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,26,'BM','Bermudes');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,27,'BT','Bhoutan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,28,'BY','Bielorussie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,29,'MM','Birmanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,30,'BO','Bolivie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,31,'BA','Bosnie-Herzegovine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,32,'BW','Botswana');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,33,'BR','Bresil');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,34,'BN','Brunei');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,35,'BG','Bulgarie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,36,'BF','Burkina Faso');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,37,'BI','Burundi');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,38,'KH','Cambodge');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,39,'CM','Cameroun');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,40,'CA','Canada');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,41,'CV','Cap-Vert');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,42,'CL','Chili');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,43,'CN','Chine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,44,'CY','Chypre');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,45,'CO','Colombie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,46,'KM','Comores');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,47,'CG','Congo');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,48,'CD','Congo (Republique democratique du )');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,49,'KP','Coree du Nord');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,50,'KR','Coree du Sud');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,51,'CR','Costa Rica');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,52,'CI','Cote d''Ivoire');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,53,'HR','Croatie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,54,'CU','Cuba');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,55,'DK','Danemark');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,56,'DJ','Djibouti');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,57,'DM','Dominique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,58,'EG','egypte');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,59,'AE','emirats arabes unis');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,60,'EC','equateur');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,61,'ER','erythree');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,62,'ES','Espagne');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,63,'EE','Estonie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,64,'US','etats-Unis');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,65,'ET','ethiopie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,66,'FJ','Fidji');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,67,'FI','Finlande');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,68,'FR','France');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,69,'GA','Gabon');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,70,'GM','Gambie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,71,'GE','Georgie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,72,'GH','Ghana');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,73,'GI','Gibraltar');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,74,'GR','Grece');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,75,'GD','Grenade');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,76,'GL','Groenland');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,77,'GP','Guadeloupe');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,78,'GU','Guam');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,79,'GT','Guatemala');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,80,'GN','Guinee');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,81,'GQ','Guinee equatoriale');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,82,'GW','Guinee-Bissao');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,83,'GY','Guyana');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,84,'GF','Guyane francaise');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,85,'HT','Haiti');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,86,'HN','Honduras');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,87,'HK','Hong Kong');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,88,'HU','Hongrie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,89,'CX','Ile Christmas');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,90,'NF','Ile Norfolk');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,91,'KY','Iles Cayman');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,92,'CK','Iles Cook');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,93,'CC','Iles des Cocos');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,94,'FK','Iles Falkland');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,95,'FO','Iles Feroe');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,96,'MH','Iles Marshall');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,97,'PN','Iles Pitcairn');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,98,'SB','Iles Salomon');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,99,'SJ','Iles Svalbard et Jan Mayen');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,100,'TC','Iles Turks-et-Caicos');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,101,'VI','Iles Vierges americaines');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,102,'VG','Iles Vierges britanniques');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,103,'IN','Inde');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,104,'ID','Indonesie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,105,'IR','Iran');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,106,'IQ','Iraq');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,107,'IE','Irlande');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,108,'IS','Islande');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,109,'IL','Israel');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,110,'IT','Italie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,111,'JM','Jamaique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,112,'JP','Japon');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,113,'JO','Jordanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,114,'KZ','Kazakhstan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,115,'KE','Kenya');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,116,'KG','Kirghizistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,117,'KI','Kiribati');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,118,'KW','Koweit');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,119,'LA','Laos');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,120,'LS','Lesotho');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,121,'LV','Lettonie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,122,'LB','Liban');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,123,'LR','Liberia');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,124,'LY','Libye');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,125,'LI','Liechtenstein');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,126,'LT','Lituanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,127,'LU','Luxembourg');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,128,'MO','Macao');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,129,'MK','Macedoine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,130,'MG','Madagascar');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,131,'MY','Malaisie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,132,'MW','Malawi');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,133,'MV','Maldives');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,134,'ML','Mali');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,135,'MT','Malte');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,136,'MP','Mariannes du Nord');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,137,'MA','Maroc');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,138,'MQ','Martinique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,139,'MU','Maurice');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,140,'MR','Mauritanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,141,'YT','Mayotte');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,142,'MX','Mexique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,143,'FM','Micronesie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,144,'MD','Moldavie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,145,'MC','Monaco');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,146,'MN','Mongolie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,147,'MS','Montserrat');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,148,'MZ','Mozambique');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,149,'NA','Namibie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,150,'NR','Nauru');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,151,'NP','Nepal');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,152,'NI','Nicaragua');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,153,'NE','Niger');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,154,'NG','Nigeria');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,155,'NU','Nioue');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,156,'NO','Norvege');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,157,'NC','Nouvelle-Caledonie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,158,'NZ','Nouvelle-Zelande');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,159,'OM','Oman');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,160,'UG','Ouganda');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,161,'UZ','Ouzbekistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,162,'PK','Pakistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,163,'PA','Panama');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,164,'PG','Papouasie-Nouvelle-Guinee');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,165,'PY','Paraguay');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,166,'NL','Pays-Bas');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,167,'PE','Perou');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,168,'PH','Philippines');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,169,'PL','Pologne');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,170,'PF','Polynesie francaise');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,171,'PR','Porto Rico');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,172,'PT','Portugal');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,173,'QA','Qatar');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,174,'CF','Republique centrafricaine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,175,'DO','Republique dominicaine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,176,'CZ','Republique tcheque');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,177,'RE','Reunion');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,178,'RO','Roumanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,179,'GB','Royaume-Uni');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,180,'RU','Russie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,181,'RW','Rwanda');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,182,'EH','Sahara occidental35');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,183,'KN','Saint-Christophe-et-Nieves');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,184,'SH','Sainte-Helene');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,185,'LC','Sainte-Lucie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,186,'SM','Saint-Marin');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,187,'PM','Saint-Pierre-et-Miquelon');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,188,'VA','Saint-Siege');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,189,'VC','Saint-Vincent-et-les-Grenadines');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,190,'SV','Salvador');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,191,'WS','Samoa');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,192,'AS','Samoa americaines');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,193,'ST','Sao Tome-et-Principe');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,194,'SN','Senegal');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,195,'YU','Serbie-et-Montenegro');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,196,'SC','Seychelles');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,197,'SL','Sierra Leone');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,198,'SG','Singapour');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,199,'SK','Slovaquie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,200,'SI','Slovenie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,201,'SO','Somalie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,202,'SD','Soudan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,203,'LK','Sri Lanka');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,204,'SE','Suede');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,205,'CH','Suisse');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,206,'SR','Suriname');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,207,'SZ','Swaziland');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,208,'SY','Syrie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,209,'TJ','Tadjikistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,210,'TW','Taiwan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,211,'TZ','Tanzanie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,212,'TD','Tchad');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,213,'TH','Thailande');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,214,'TL','Timor oriental');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,215,'TG','Togo');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,216,'TK','Tokelaou');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,217,'TO','Tonga');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,218,'TT','Trinite-et-Tobago');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,219,'TN','Tunisie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,220,'TM','Turkmenistan');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,221,'TR','Turquie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,222,'TV','Tuvalu');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,223,'UA','Ukraine');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,224,'UY','Uruguay');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,225,'VU','Vanuatu');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,226,'VE','Venezuela');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,227,'VN','Viet Nam');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,228,'WF','Wallis-et-Futuna');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,229,'YE','Yemen');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,230,'ZM','Zambie');
INSERT INTO COUNTRY (CREATE_DATE, MOD_DATE, MOD_BY,COUNTRY_ID,DOMAIN, NAME) VALUES(now(), now(),1,231,'ZW','Zimbabwe');


INSERT INTO USER_GROUP(CREATE_DATE, MOD_DATE, MOD_BY, USER_GROUP_ID, NAME) VALUES (now(), now(), 1, 1, 'Admin');
INSERT INTO USER_GROUP(CREATE_DATE, MOD_DATE, MOD_BY, USER_GROUP_ID, NAME) VALUES (now(), now(), 1, 2, 'Doctor');
INSERT INTO USER_GROUP(CREATE_DATE, MOD_DATE, MOD_BY, USER_GROUP_ID, NAME) VALUES (now(), now(), 1, 3, 'Nurse');
INSERT INTO USER_GROUP(CREATE_DATE, MOD_DATE, MOD_BY, USER_GROUP_ID, NAME) VALUES (now(), now(), 1, 20, 'Patient');

INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 1, 'Sunday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 2, 'Monday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 3, 'Tuesday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 4, 'Wednesday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 5, 'Thursday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 6, 'Friday');
INSERT INTO WEEK_DAY(CREATE_DATE, MOD_DATE, MOD_BY, WEEK_DAY_ID, NAME) VALUES (now(), now(), 1, 7, 'Saturday');

INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 1, 'Medicine');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 2, 'BED');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 3, 'SYMPTOM');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 4, 'ALLERGY');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 5, 'VACCINE');
INSERT INTO CATEGORY(CREATE_DATE, MOD_DATE, MOD_BY, CATEGORY_ID, NAME) VALUES (now(), now(), 1, 6, 'SERVICE_TARIF');

INSERT INTO USERS (USER_GROUP_ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, SEX, BIRTH_DATE) VALUES (1, 'admin', '$2a$10$TpGAfZgpYQWWA1/b08miJ.tZs06jIz60LeKO5PVU1ogVB2snOf2A2', 'Admin', 'Admin', 'M', NOW());
ALTER TABLE CATEGORY AUTO_INCREMENT=101;

INSERT INTO DISCHARGE_REASON(CREATE_DATE, MOD_DATE, MOD_BY, DISCHARGE_REASON_ID, NAME) VALUES (now(), now(), 1, 1, 'Patient Cured');
INSERT INTO DISCHARGE_REASON(CREATE_DATE, MOD_DATE, MOD_BY, DISCHARGE_REASON_ID, NAME) VALUES (now(), now(), 1, 2, 'Patient Deceased');
INSERT INTO DISCHARGE_REASON(CREATE_DATE, MOD_DATE, MOD_BY, DISCHARGE_REASON_ID, NAME) VALUES (now(), now(), 1, 3, 'Patient Transferred');
INSERT INTO DISCHARGE_REASON(CREATE_DATE, MOD_DATE, MOD_BY, DISCHARGE_REASON_ID, NAME) VALUES (now(), now(), 1, 4, 'Patient Terminated w/o Approval');

INSERT INTO DOCTOR_ORDER_STATUS(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_STATUS_ID, NAME) VALUES (now(), now(), 1, 1, 'PENDING');
INSERT INTO DOCTOR_ORDER_STATUS(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_STATUS_ID, NAME) VALUES (now(), now(), 1, 2, 'INPROGRESS');
INSERT INTO DOCTOR_ORDER_STATUS(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_STATUS_ID, NAME) VALUES (now(), now(), 1, 3, 'COMPLETED');
INSERT INTO DOCTOR_ORDER_STATUS(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_STATUS_ID, NAME) VALUES (now(), now(), 1, 4, 'CLOSED');

INSERT INTO DOCTOR_ORDER_TYPE(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_TYPE_ID, NAME) VALUES (now(), now(), 1, 1, 'Pharmacy');
INSERT INTO DOCTOR_ORDER_TYPE(CREATE_DATE, MOD_DATE, MOD_BY, DOCTOR_ORDER_TYPE_ID, NAME) VALUES (now(), now(), 1, 2, 'Laboratory');

INSERT INTO PRESCRIPTION_TYPE(PRESCRIPTION_TYPE_ID, NAME) VALUES (1, 'New');
INSERT INTO PRESCRIPTION_TYPE(PRESCRIPTION_TYPE_ID, NAME) VALUES (2, 'Old');


INSERT INTO REPORT (NAME, DESCRIPTION, STATUS, CREATE_DATE,MOD_DATE, MOD_BY ) 
VALUES ('bill','Bill Report', 1, NOW(), NOW(), 1 );


INSERT INTO RELIGION (NAME, DESCRIPTION, CREATE_DATE, MOD_DATE, MOD_BY, STATUS)
VALUES ('Judaïsme','Judaïsme',NOW(), NOW(), 1, 1),
('Christianisme','Christianisme',NOW(), NOW(), 1, 1),
('Mithraïsme','Mithraïsme',NOW(), NOW(), 1, 1),
('Islam','Islam',NOW(), NOW(), 1, 1),
('Confucianisme','Confucianisme',NOW(), NOW(), 1, 1),
('Bouddhisme','Bouddhisme',NOW(), NOW(), 1, 1),
('Jaïnisme','Jaïnisme',NOW(), NOW(), 1, 1),
('Zoroastrisme','Zoroastrisme',NOW(), NOW(), 1, 1),
('Taoïsme','Taoïsme',NOW(), NOW(), 1, 1),
('Hindouisme','Hindouisme',NOW(), NOW(), 1, 1),
('Animisme','Animisme',NOW(), NOW(), 1, 1),
('Autre','Autre',NOW(), NOW(), 1, 1);


INSERT INTO OCCUPATION (NAME, DESCRIPTION, CREATE_DATE, MOD_DATE, MOD_BY, STATUS)
VALUES ('Agricole','Agricole',NOW(), NOW(), 1, 1),
('Agroalimentaire','Agroalimentaire',NOW(), NOW(), 1, 1),
('Bancaire et financier','Bancaire et financier',NOW(), NOW(), 1, 1),
('Energie','Energie',NOW(), NOW(), 1, 1),
('Communication et des médias','Communication et des médias',NOW(), NOW(), 1, 1),
('Distribution','Distribution',NOW(), NOW(), 1, 1),
('Recherche','Recherche',NOW(), NOW(), 1, 1),
('Santé','Santé',NOW(), NOW(), 1, 1),
('Constructions mécaniques','Constructions mécaniques',NOW(), NOW(), 1, 1),
('Industries chimiques','Industries chimiques',NOW(), NOW(), 1, 1),
('Loisirs et du tourisme','Loisirs et du tourisme',NOW(), NOW(), 1, 1),
('Matières premières ','Matières premières ',NOW(), NOW(), 1, 1),
('Services','Services',NOW(), NOW(), 1, 1),
('Transports','Transports',NOW(), NOW(), 1, 1),
('Bâtiment','Bâtiment',NOW(), NOW(), 1, 1),
('Electronique','Electronique',NOW(), NOW(), 1, 1),
('Informatique','Informatique',NOW(), NOW(), 1, 1),
('Métallurgique','Métallurgique',NOW(), NOW(), 1, 1),
('Textile','Textile',NOW(), NOW(), 1, 1),
('Autre','Autre',NOW(), NOW(), 1, 1);

UPDATE OCCUPATION SET STATUS =0;
UPDATE RELIGION SET STATUS =0;


INSERT INTO ROLE (ROLE_ID, NAME, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (1, 'ADMIN', 'Administrator', 0, NOW(), NOW(), 1);

INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (1, 1, 1, 0, NOW(), NOW(), 1);

INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (1, 'Dashboard', '/admin/dashboard', 'Administrator', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (2, 'Patient Details', '/admin/patientDetails', 'Details of patient', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (3, 'Patient Kiosk', '/admin/patientKiosk', 'Kiosk details of patient', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (4, 'Patient List', '/admin/patientList', 'List of patients', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (5, 'Employee Details', '/admin/employeeDetails', 'Details of employee', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (6, 'Employee List', '/admin/employeeList', 'List of employees', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (7, 'Admission Details', '/admin/admissionDetails', 'Details of an admission', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (8, 'Admission List', '/admin/admissionList', 'List of admissions', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (9, 'Change Bed', '/admin/bedTransfer?transferType=BED', 'Change of bed', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (10, 'Change Doctor', '/admin/bedTransfer?transferType=DOCTOR', 'Change of doctor', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (11, 'Add schedule', '/admin/scheduleDetails', 'Add schedule', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (12, 'List schedules', '/admin/scheduleList', 'List schedules', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (13, 'Appointments', '/admin/appointmentScheduler', 'Appointments', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (14, 'Add visit', '/admin/visitDetails', 'Add a visit', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (15, 'List visits', '/admin/visitList', 'List visits', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (16, 'Wait List', '/admin/waitingList', 'Waiting List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (17, 'Add a test', '/admin/investigationDetails', 'Add a test', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (18, 'List tests', '/admin/investigationList', 'List tests', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (19, 'Add Exam', '/admin/radInvestigationDetails', 'Add Exam', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (20, 'List exams', '/admin/radInvestigationList', 'List of exams', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (21, 'Add a bill', '/admin/billDetails', 'Add a bill', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (22, 'List bills', '/admin/billList', 'List bills', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (23, 'Add Tarif', '/admin/serviceDetails', 'Add Tarif', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (24, 'List Tarifs', '/admin/serviceList', 'Tarif List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (25, 'Add a package', '/admin/packageDetails', 'Add a package', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (26, 'Package List', '/admin/packageList', 'Package List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (27, 'Add Medication Order', '/admin/purchaseOrderDetails', 'Order medication', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (28, 'Medication Order List', '/admin/purchaseOrderList', 'Medication Order List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (29, 'Add Receive Order', '/admin/receiveOrderDetails', 'Add Receive Order', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (30, 'Receive Order List', '/admin/receiveOrderList', 'Receive Order List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (31, 'Add Medication Sale', '/admin/patientSaleDetails', 'Add Medication Sale', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (32, 'Medication Sale List', '/admin/patientSaleList', 'Medication Sale List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (33, 'Add Sale Return', '/admin/saleReturnDetails', 'Add Sale Return', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (34, 'Sale Return List', '/admin/saleReturnList', 'Sale Return List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (35, 'Report birth', '/admin/birthReportDetails', 'Report birth', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (36, 'Birth List', '/admin/birthReportList', 'List of births', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (37, 'Report a Death', '/admin/deathReportDetails', 'Report a Death', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (38, 'Death Report List', '/admin/deathReportList', 'Death Report List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (39, 'Add Request', '/admin/enquiryDetails', 'Add Request', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (40, 'Request List', '/admin/enquiryList', 'Request List', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (41, 'Room and beds', '/admin/adminBedStatus', 'Room and beds configuration', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (42, 'Reference Config', '/admin/adminReference', 'Reference Configuration', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (43, 'Website Config', '/admin/adminWebsite', 'Website Configuration', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (44, 'Radiology Config', '/admin/adminRadiologyConfig', 'Radiology Configuration', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (45, 'Security Config', '/admin/adminAuthorization', 'Security Configuration', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (46, 'Assign Role', '/admin/userRoleAssignment', 'Assign Role to User', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (47, 'Assign Resource', '/admin/permission', 'Assign Resource to Role', 0, NOW(), NOW(), 1);

INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (48, 'SECURITY_CONFIG_ROLES', '', 'Security -> Config -> Roles', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (49, 'SECURITY_CONFIG_RESOURCES', '', 'Security -> Config -> Resources', 0, NOW(), NOW(), 1);
INSERT INTO RESOURCE (RESOURCE_ID, NAME, URL_PATH, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (50, 'SECURITY_CONFIG_MENUS', '', 'Security -> Config -> Menus', 0, NOW(), NOW(), 1);



INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (1, null, 1, 'EN', 'Dashboard', 'fa fa-fw fa-home', 0, 1, 'Dashboard', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (2, null, null, 'EN', 'Patients', 'fa fa-wheelchair', 0, 2, 'Patients', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (3, 2, 2, 'EN', 'Patient Details', 'fa fa-plus', 1, 3, 'Patient Details', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (4, 2, 3, 'EN', 'Patient Kiosk', 'fa fa-plus', 1, 4, 'Patient Kiosk', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (5, 2, 4, 'EN', 'Patient List', 'fa fa-search', 1, 5, 'Patient List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (6, null, null, 'EN', 'Employees', 'fa fa-user-md', 0, 6, 'Employees', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (7, 6, 5, 'EN', 'Employee Details', 'fa fa-plus', 1, 7, 'Employee Details', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (8, 6, 6, 'EN', 'Employee List', 'fa fa-search', 1, 8, 'Employee List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (9, null, null, 'EN', 'Admission', 'fa fa-ambulance', 0, 9, 'Admission', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (10, 9, 7, 'EN', 'Admit a patient', 'fa fa-plus', 1, 10, 'Admit a patient', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (11, 9, 8, 'EN', 'Admission List', 'fa fa-search', 1, 11, 'Admission List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (12, 9, 9, 'EN', 'Change Bed', 'fa fa-edit', 1, 12, 'Change Bed', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (13, 9, 10, 'EN', 'Change Doctor', 'fa fa-edit', 1, 13, 'Change Doctor', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (14, null, null, 'EN', 'Appointment', 'fa fa-calendar', 0, 14, 'Appointment', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (15, 14, 11, 'EN', 'Add schedule', 'fa fa-plus', 1, 15, 'Add schedule', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (16, 14, 12, 'EN', 'Schedule List', 'fa fa-search', 1, 16, 'Schedule List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (17, 14, 13, 'EN', 'Appointments', 'fa fa-calendar-check-o', 1, 17, 'Appointments', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (18, null, null, 'EN', 'Visits', 'fa fa-user-md', 0, 18, 'Visits', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (19, 18, 14, 'EN', 'Add visit', 'fa fa-plus', 1, 19, 'Add Visit', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (20, 18, 15, 'EN', 'Visit List', 'fa fa-search', 1, 20, 'Visit List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (21, 18, 16, 'EN', 'Wait list', 'fa fa-search', 1, 21, 'Wait list', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (22, null, null, 'EN', 'Lab', 'fa fa-stethoscope', 0, 22, 'Lab', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (23, 22, 17, 'EN', 'Add Test', 'fa fa-plus', 1, 23, 'Add Test', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (24, 22, 18, 'EN', 'Test List', 'fa fa-search', 1, 24, 'Test List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (25, null, null, 'EN', 'Radiology', 'fas fa-x-ray', 0, 25, 'Radiology', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (26, 25, 19, 'EN', 'Add Exam', 'fa fa-plus', 1, 26, 'Add Exam', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (27, 25, 20, 'EN', 'Exam List', 'fa fa-search', 1, 27, 'Exam List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (28, null, null, 'EN', 'Billing', 'fa fa-money', 0, 28, 'Billing', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (29, 28, 21, 'EN', 'Add Bill', 'fa fa-plus', 1, 29, 'Add Bill', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (30, 28, 22, 'EN', 'Bill List', 'fa fa-search', 1, 30, 'Bill List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (31, 28, 23, 'EN', 'Add Tarif', 'fa fa-plus', 1, 31, 'Add Tarif', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (32, 28, 24, 'EN', 'Tarif List', 'fa fa-search', 1, 32, 'Tarif List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (33, 28, 25, 'EN', 'Add Package', 'fa fa-plus', 1, 33, 'Add Package', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (34, 28, 26, 'EN', 'Package List', 'fa fa-search', 1, 34, 'Package List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (35, null, null, 'EN', 'Pharmacy', 'fa fa-heart', 0, 35, 'Pharmacy', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (36, 35, 27, 'EN', 'Add Medication Order', 'fa fa-plus', 1, 36, 'Add Medication Order', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (37, 35, 28, 'EN', 'Medication Order List', 'fa fa-search', 1, 37, 'Medication Order List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (38, 35, 29, 'EN', 'Add Receive Order', 'fa fa-plus', 1, 38, 'Add Receive Order', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (39, 35, 30, 'EN', 'Receive Order List', 'fa fa-search', 1, 39, 'Receive Order List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (40, 35, 31, 'EN', 'Add Medication Sale', 'fa fa-plus', 1, 40, 'Add Medication Sale', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (41, 35, 32, 'EN', 'Medication Sale List', 'fa fa-search', 1, 41, 'Medication Sale List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (42, 35, 33, 'EN', 'Add Sale Return', 'fa fa-plus', 1, 42, 'Add Sale Return', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (43, 35, 34, 'EN', 'Sale Return List', 'fa fa-search', 1, 43, 'Sale Return List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (44, null, null, 'EN', 'Hospital Activities', 'fa fa-hospital-o', 0, 44, 'Hospital Activities', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (45, 44, 35, 'EN', 'Report Birth', 'fa fa-plus', 1, 45, 'Report birth', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (46, 44, 36, 'EN', 'Birth List', 'fa fa-search', 1, 46, 'Birth List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (47, 44, 37, 'EN', 'Report Death', 'fa fa-plus', 1, 47, 'Report Death', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (48, 44, 38, 'EN', 'Death List', 'fa fa-search', 1, 48, 'Death List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (49, 44, 39, 'EN', 'Add Request', 'fa fa-plus', 1, 49, 'Add Request', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (50, 44, 40, 'EN', 'Request List', 'fa fa-search', 1, 50, 'Request List', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (51, null, null, 'EN', 'Configuration', 'fa fa-cogs', 0, 51, 'Configuration', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (52, 51, 41, 'EN', 'Room and beds', 'fa fa-bed', 1, 52, 'Room and beds', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (53, 51, 42, 'EN', 'Reference Config', 'fa fa-fw fa-paint-brush', 1, 53, 'Reference Config', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (54, 51, 43, 'EN', 'Website Config', 'fa fa-fw fa-globe', 1, 54, 'Website Config', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (55, 51, 44, 'EN', 'Radiology Config', 'fas fa-x-ray', 1, 55, 'Radiology Config', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (56, null, null, 'EN', 'Security', 'fa fa-lock', 0, 56, 'Security', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (57, 56, 45, 'EN', 'Security Conf', 'fa fa-cogs', 1, 57, 'Security Conf', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (58, 56, 46, 'EN', 'Assign Role to User', 'fa fa-plus', 1, 58, 'Assign Role to User', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (59, 56, 47, 'EN', 'Permission', 'fa fa-plus', 1, 59, 'Permission', 0, NOW(), NOW(), 1);


INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (501, null, 1, 'FR', 'Dashboard', 'fa fa-fw fa-home', 0, 501, 'Dashboard', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (502, null, null, 'FR', 'Patients', 'fa fa-wheelchair', 0, 502, 'Patients', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (503, 502, 2, 'FR', 'Ajouter un patient', 'fa fa-plus', 1, 503, 'Ajouter un patient', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (504, 502, 3, 'FR', 'Kiok Patient', 'fa fa-plus', 1, 504, 'Kiosk Patient', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (505, 502, 4, 'FR', 'Liste des patients', 'fa fa-search', 1, 505, 'Liste des patients', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (506, null, null, 'FR', 'Personnel', 'fa fa-user-md', 0, 506, 'Personnel', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (507, 506, 5, 'FR', 'Ajouter un personnel', 'fa fa-plus', 1, 507, 'Ajouter un personnel', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (508, 506, 6, 'FR', 'Liste du personnel', 'fa fa-search', 1, 508, 'Liste du personnel', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (509, null, null, 'FR', 'Admission', 'fa fa-ambulance', 0, 509, 'Admission', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (510, 509, 7, 'FR', 'Admettre un patient', 'fa fa-plus', 1, 510, 'Admettre un patient', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (511, 509, 8, 'FR', 'Liste des admissions', 'fa fa-search', 1, 511, 'Liste des admissions', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (512, 509, 9, 'FR', 'Changer de lit', 'fa fa-edit', 1, 512, 'Changer de lit', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (513, 509, 10, 'FR', 'Changer de mÃ©decin', 'fa fa-edit', 1, 513, 'Changer de mÃ©decin', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (514, null, null, 'FR', 'Rendez-vous', 'fa fa-calendar', 0, 514, 'Rendez-vous', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (515, 514, 11, 'FR', 'Ajouter un horaire', 'fa fa-plus', 1, 515, 'Ajouter un horaire', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (516, 514, 12, 'FR', 'Liste des horaires', 'fa fa-search', 1, 516, 'Liste des horaires', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (517, 514, 13, 'FR', 'Les Rendez-vous', 'fa fa-calendar-check-o', 1, 517, 'Les Rendez-vous', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (518, null, null, 'FR', 'Visites', 'fa fa-user-md', 0, 518, 'Visites', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (519, 518, 14, 'FR', 'Ajouter une visite', 'fa fa-plus', 1, 519, 'Ajouter une visite', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (520, 518, 15, 'FR', 'Liste des visites', 'fa fa-search', 1, 520, 'Liste des visites', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (521, 518, 16, 'FR', 'Liste d''attente', 'fa fa-search', 1, 521, 'Liste d''attente', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (522, null, null, 'FR', 'Laboratoire', 'fa fa-stethoscope', 0, 522, 'Laboratoire', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (523, 522, 17, 'FR', 'Ajouter un test', 'fa fa-plus', 1, 523, 'Ajouter un test', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (524, 522, 18, 'FR', 'Liste des tests', 'fa fa-search', 1, 524, 'Liste des tests', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (525, null, null, 'FR', 'Radiologie', 'fas fa-x-ray', 0, 525, 'Radiologie', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (526, 525, 19, 'FR', 'Ajouter un examen', 'fa fa-plus', 1, 526, 'Ajouter un examen', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (527, 525, 20, 'FR', 'Liste des examens', 'fa fa-search', 1, 527, 'Liste des examens', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (528, null, null, 'FR', 'Facturation', 'fa fa-money', 0, 528, 'Facturation', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (529, 528, 21, 'FR', 'Nouvelle facture', 'fa fa-plus', 1, 529, 'Nouvelle facture', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (530, 528, 22, 'FR', 'Anciennes Factures', 'fa fa-search', 1, 530, 'Anciennes Factures', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (531, 528, 23, 'FR', 'Ajouter un tarif', 'fa fa-plus', 1, 531, 'Ajouter un tarif', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (532, 528, 24, 'FR', 'Liste des tarifs', 'fa fa-search', 1, 532, 'Liste des tarifs', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (533, 528, 25, 'FR', 'Ajouter un paquet', 'fa fa-plus', 1, 533, 'Ajouter un paquet', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (534, 528, 26, 'FR', 'Liste des paquets', 'fa fa-search', 1, 534, 'Liste des paquets', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (535, null, null, 'FR', 'Pharmacie', 'fa fa-heart', 0, 535, 'Pharmacie', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (536, 535, 27, 'FR', 'Commander mÃ©dicament', 'fa fa-plus', 1, 536, 'Commander mÃ©dicament', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (537, 535, 28, 'FR', 'Liste des commandes', 'fa fa-search', 1, 537, 'Liste des commandes', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (538, 535, 29, 'FR', 'RÃ©ception de commande', 'fa fa-plus', 1, 538, 'RÃ©ception de commande', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (539, 535, 30, 'FR', 'Liste des receptions', 'fa fa-search', 1, 539, 'Liste des receptions', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (540, 535, 31, 'FR', 'Ajouter une vente', 'fa fa-plus', 1, 540, 'Ajouter une vente', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (541, 535, 32, 'FR', 'Liste des ventes', 'fa fa-search', 1, 541, 'Liste des ventes', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (542, 535, 33, 'FR', 'Ajouter un retour achat', 'fa fa-plus', 1, 542, 'Ajouter un retour achat', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (543, 535, 34, 'FR', 'Liste des retours', 'fa fa-search', 1, 543, 'Liste des retours', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (544, null, null, 'FR', 'ActivitÃ©s', 'fa fa-hospital-o', 0, 544, 'ActivitÃ©s', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (545, 544, 35, 'FR', 'DÃ©clarer une naissance', 'fa fa-plus', 1, 545, 'DÃ©clarer une naissance', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (546, 544, 36, 'FR', 'Liste des naissances', 'fa fa-search', 1, 546, 'Liste des naissances', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (547, 544, 37, 'FR', 'Declarer un dÃ©cÃ¨s', 'fa fa-plus', 1, 547, 'Declarer un dÃ©cÃ¨s', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (548, 544, 38, 'FR', 'Liste des dÃ©cÃ¨s', 'fa fa-search', 1, 548, 'Liste des dÃ©cÃ¨s', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (549, 544, 39, 'FR', 'Ajouter une requÃªte', 'fa fa-plus', 1, 549, 'Ajouter une requÃªte', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (550, 544, 40, 'FR', 'Liste des requÃªtes', 'fa fa-search', 1, 550, 'Liste des requÃªtes', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (551, null, null, 'FR', 'Configuration', 'fa fa-cogs', 0, 551, 'Configuration', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (552, 551, 41, 'FR', 'Chambres et lits', 'fa fa-bed', 1, 552, 'Chambres et lits', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (553, 551, 42, 'FR', 'Config. des RÃ©fÃ©rences', 'fa fa-fw fa-paint-brush', 1, 553, 'Config. des RÃ©fÃ©rences', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (554, 551, 43, 'FR', 'Config. du site web', 'fa fa-fw fa-globe', 1, 554, 'Config. du site web', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (555, 551, 44, 'FR', 'Config. Radiologie', 'fas fa-x-ray', 1, 555, 'Config. Radiologie', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (556, null, null, 'FR', 'SecuritÃ©', 'fa fa-lock', 0, 556, 'SecuritÃ©', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (557, 556, 45, 'FR', 'Config. SecuritÃ©', 'fa fa-cogs', 1, 557, 'Config. SecuritÃ©', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (558, 556, 46, 'FR', 'Assigner Role', 'fa fa-plus', 1, 558, 'Assigner Role', 0, NOW(), NOW(), 1);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, PARENT_ID, RESOURCE_ID, LANGUAGE, LABEL, ICON, LEVEL, MI_ORDER, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (559, 556, 47, 'FR', 'Permission', 'fa fa-plus', 1, 559, 'Permission', 0, NOW(), NOW(), 1);



INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (1, 1, 1, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (2, 1, 2, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (3, 1, 3, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (4, 1, 4, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (5, 1, 5, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (6, 1, 6, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (7, 1, 7, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (8, 1, 8, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (9, 1, 9, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (10, 1, 10, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (11, 1, 11, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (12, 1, 12, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (13, 1, 13, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (14, 1, 14, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (15, 1, 15, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (16, 1, 16, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (17, 1, 17, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (18, 1, 18, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (19, 1, 19, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (20, 1, 20, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (21, 1, 21, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (22, 1, 22, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (23, 1, 23, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (24, 1, 24, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (25, 1, 25, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (26, 1, 26, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (27, 1, 27, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (28, 1, 28, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (29, 1, 29, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (30, 1, 30, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (31, 1, 31, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (32, 1, 32, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (33, 1, 33, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (34, 1, 34, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (35, 1, 35, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (36, 1, 36, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (37, 1, 37, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (38, 1, 38, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (39, 1, 39, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (40, 1, 40, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (41, 1, 41, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (42, 1, 42, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (43, 1, 43, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (44, 1, 44, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (45, 1, 45, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (46, 1, 46, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (47, 1, 47, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);


INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (48, 1, 48, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (49, 1, 49, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);
INSERT INTO PERMISSION (PERMISSION_ID, ROLE_ID, RESOURCE_ID, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, DESCRIPTION, STATUS, CREATE_DATE, MOD_DATE, MOD_BY) VALUES (50, 1, 50, 'Y', 'Y', 'Y', 'Y', '', 0, NOW(), NOW(), 1);


COMMIT;
